In [ ]:
import numpy
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,Conv2D,MaxPooling2D
from keras.constraints import maxnorm
from tensorflow.keras.optimizers import SGD
from keras.utils import np_utils 

In [ ]:
from keras.datasets import cifar100
# let's load data 
(X_train, y_train), (X_test, y_test) = cifar100.load_data()
print(X_train.shape)
print(y_train.shape)

169017344/169001437 [==============================] - 3s 0us/step
(50000, 32, 32, 3)
(50000, 1)


In [ ]:
#normalizing inputs from 0-255 to 0.0-1.0 
X_train = X_train.astype('float32') 
X_test = X_test.astype('float32') 
X_train = X_train / 255.0 
X_test = X_test / 255.0

In [ ]:
# one hot encode outputs 
y_train = np_utils.to_categorical(y_train) 
y_test = np_utils.to_categorical(y_test) 
num_classes = y_test.shape[1]
print(y_train.shape)

(50000, 100)


In [ ]:
# Create the model 
model = Sequential()

model.add(Conv2D(32, (3, 3), input_shape=(32,32,3), activation='relu', padding='same')) 
model.add(Conv2D(32, (3, 3), activation='relu', padding='same')) 
model.add(MaxPooling2D(pool_size=(2, 2))) 
model.add(Conv2D(64, (3, 3), activation='relu', padding='same')) 
model.add(Conv2D(64, (3, 3), activation='relu', padding='same')) 
model.add(MaxPooling2D(pool_size=(2, 2))) 
model.add(Conv2D(128, (3, 3), activation='relu', padding='same')) 
model.add(Conv2D(128, (3, 3), activation='relu', padding='same')) 
model.add(MaxPooling2D(pool_size=(2, 2))) 
model.add(Flatten()) 
model.add(Dropout(0.4)) 
model.add(Dense(1024, activation='relu', kernel_constraint=maxnorm(3))) 
model.add(Dense(512, activation='relu', kernel_constraint=maxnorm(3))) 
model.add(Dense(num_classes, activation='softmax'))

In [ ]:
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 32, 32, 32)        896       
                                                                 
 conv2d_7 (Conv2D)           (None, 32, 32, 32)        9248      
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 16, 16, 32)       0         
 2D)                                                             
                                                                 
 conv2d_8 (Conv2D)           (None, 16, 16, 64)        18496     
                                                                 
 conv2d_9 (Conv2D)           (None, 16, 16, 64)        36928     
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 8, 8, 64)         0         
 2D)                                                  

In [ ]:
# Compile model 
lrate = 0.01 
epochs = 100
decay = lrate/epochs 
sgd = SGD(lr=lrate, momentum=0.9, decay=decay, nesterov=False) 
model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


In [ ]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs= epochs, batch_size = 32) 
# Final evaluation of the model 
scores = model.evaluate(X_test, y_test, verbose=0) 
print("Accuracy: %.2f%%" % (scores[1]*100))

Epoch 1/100
1563/1563 [==============================] - 12s 7ms/step - loss: 4.2251 - accuracy: 0.0514 - val_loss: 3.7519 - val_accuracy: 0.1188
Epoch 2/100
1563/1563 [==============================] - 10s 7ms/step - loss: 3.5617 - accuracy: 0.1523 - val_loss: 3.2307 - val_accuracy: 0.2205
Epoch 3/100
1563/1563 [==============================] - 10s 6ms/step - loss: 3.1049 - accuracy: 0.2384 - val_loss: 2.8823 - val_accuracy: 0.2866
Epoch 4/100
1563/1563 [==============================] - 10s 6ms/step - loss: 2.7628 - accuracy: 0.3012 - val_loss: 2.6608 - val_accuracy: 0.3281
Epoch 5/100
1563/1563 [==============================] - 11s 7ms/step - loss: 2.4999 - accuracy: 0.3574 - val_loss: 2.4832 - val_accuracy: 0.3688
Epoch 6/100
1563/1563 [==============================] - 10s 6ms/step - loss: 2.2724 - accuracy: 0.4043 - val_loss: 2.4002 - val_accuracy: 0.3883
Epoch 7/100
1563/1563 [==============================] - 10s 6ms/step - loss: 2.0627 - accuracy: 0.4486 - val_loss: 2.2714 -

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix
pred = model.predict(X_test)
pred = np.argmax(pred, axis = 1) 
label = np.argmax(y_test,axis = 1)
r = confusion_matrix(pred, label)
print(r)

[[75  0  2 ...  0  0  0]
 [ 0 56  0 ...  0  0  0]
 [ 0  0 41 ...  0  7  1]
 ...
 [ 0  0  0 ... 48  0  0]
 [ 0  0  5 ...  0 22  1]
 [ 0  0  0 ...  0  1 50]]


https://pythonistaplanet.com/cifar-10-image-classification-using-keras/

In [ ]:
from tensorflow.keras.applications import VGG19, ResNet50

In [ ]:
from tensorflow.keras.optimizers import SGD,Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau

'Lastly import the final layers that will be added on top of the base model'
from keras.layers import Flatten,Dense,BatchNormalization,Activation,Dropout

'Import to_categorical from the keras utils package to one hot encode the labels'
from tensorflow.keras.utils import to_categorical

In [ ]:
#Build the model

'The first base model used is VGG19. The pretrained weights from the imagenet challenge are used'
base_model_1 = VGG19(include_top=False,weights='imagenet',input_shape=(32,32,3),classes=y_train.shape[1])

'For the 2nd base model we will use Resnet 50 and compare the performance against the previous one.The hypothesis is that Resnet 50 should perform better because of its deeper architecture'
base_model_2 = ResNet50(include_top=False,weights='imagenet',input_shape=(32,32,3),classes=y_train.shape[1])

In [ ]:
model_1= Sequential()
model_1.add(base_model_1)
model_1.add(Flatten())
#Add the Dense layers along with activation and batch normalization
model_1.add(Dense(1024,activation=('relu'),input_dim=512))
model_1.add(Dense(512,activation=('relu'))) 
model_1.add(Dense(256,activation=('relu'))) 
#model_1.add(Dropout(.3))#Adding a dropout layer that will randomly drop 30% of the weights
model_1.add(Dense(128,activation=('relu')))
#model_1.add(Dropout(.2))
model_1.add(Dense(y_train.shape[1],activation=('softmax'))) #This is the classification layer

In [ ]:
#Check final model summary
model_1.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 vgg19 (Functional)          (None, 1, 1, 512)         20024384  
                                                                 
 flatten_4 (Flatten)         (None, 512)               0         
                                                                 
 dense_16 (Dense)            (None, 1024)              525312    
                                                                 
 dense_17 (Dense)            (None, 512)               524800    
                                                                 
 dense_18 (Dense)            (None, 256)               131328    
                                                                 
 dense_19 (Dense)            (None, 128)               32896     
                                                                 
 dense_20 (Dense)            (None, 100)              

In [ ]:
batch_size = 128
epochs = 50
learn_rate= 0.001

sgd=SGD(lr=learn_rate,momentum=.9,nesterov=False)
adam=Adam(lr=learn_rate, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)

model_1.compile(optimizer=sgd,loss='categorical_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)
/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
model_1.fit(X_train, y_train, validation_data=(X_test, y_test), epochs= epochs, batch_size= batch_size) 

Epoch 1/50
391/391 [==============================] - 29s 73ms/step - loss: 3.9866 - accuracy: 0.1079 - val_loss: 3.1466 - val_accuracy: 0.2408
Epoch 2/50
391/391 [==============================] - 28s 73ms/step - loss: 2.7068 - accuracy: 0.3143 - val_loss: 2.4030 - val_accuracy: 0.3719
Epoch 3/50
391/391 [==============================] - 29s 73ms/step - loss: 2.2258 - accuracy: 0.4051 - val_loss: 2.1277 - val_accuracy: 0.4331
Epoch 4/50
391/391 [==============================] - 29s 74ms/step - loss: 1.9480 - accuracy: 0.4674 - val_loss: 1.9694 - val_accuracy: 0.4574
Epoch 5/50
391/391 [==============================] - 29s 74ms/step - loss: 1.7470 - accuracy: 0.5138 - val_loss: 1.8681 - val_accuracy: 0.4866
Epoch 6/50
391/391 [==============================] - 30s 76ms/step - loss: 1.5939 - accuracy: 0.5494 - val_loss: 1.8244 - val_accuracy: 0.5008
Epoch 7/50
391/391 [==============================] - 29s 75ms/step - loss: 1.4607 - accuracy: 0.5843 - val_loss: 1.8244 - val_accuracy:

In [ ]:
# Final evaluation of the model 
scores = model_1.evaluate(X_test, y_test, verbose=0) 
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 57.93%


In [ ]:
model_1= Sequential()
model_1.add(base_model_2)
model_1.add(Flatten())
#Add the Dense layers along with activation and batch normalization
model_1.add(Dense(1024,activation=('relu'),input_dim=512))
model_1.add(Dense(512,activation=('relu'))) 
model_1.add(Dense(256,activation=('relu'))) 
#model_1.add(Dropout(.3))#Adding a dropout layer that will randomly drop 30% of the weights
model_1.add(Dense(128,activation=('relu')))
#model_1.add(Dropout(.2))
model_1.add(Dense(y_train.shape[1],activation=('softmax'))) #This is the classification layer\

#Check final model summary
model_1.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 1, 1, 2048)        23587712  
                                                                 
 flatten_6 (Flatten)         (None, 2048)              0         
                                                                 
 dense_26 (Dense)            (None, 1024)              2098176   
                                                                 
 dense_27 (Dense)            (None, 512)               524800    
                                                                 
 dense_28 (Dense)            (None, 256)               131328    
                                                                 
 dense_29 (Dense)            (None, 128)               32896     
                                                                 
 dense_30 (Dense)            (None, 100)              

In [ ]:
batch_size = 128
epochs = 50
learn_rate= 0.001

sgd=SGD(lr=learn_rate,momentum=.9,nesterov=False)
adam=Adam(lr=learn_rate, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)

model_1.compile(optimizer=sgd,loss='categorical_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)
/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
model_1.fit(X_train, y_train, validation_data=(X_test, y_test), epochs= epochs, batch_size= batch_size) 

Epoch 1/50
391/391 [==============================] - 30s 66ms/step - loss: 4.4450 - accuracy: 0.0517 - val_loss: 7.5293 - val_accuracy: 0.0102
Epoch 2/50
391/391 [==============================] - 26s 65ms/step - loss: 3.5505 - accuracy: 0.2070 - val_loss: 4.3450 - val_accuracy: 0.0942
Epoch 3/50
391/391 [==============================] - 26s 68ms/step - loss: 2.6210 - accuracy: 0.3537 - val_loss: 2.6418 - val_accuracy: 0.3468
Epoch 4/50
391/391 [==============================] - 26s 67ms/step - loss: 2.0231 - accuracy: 0.4700 - val_loss: 2.3763 - val_accuracy: 0.4011
Epoch 5/50
391/391 [==============================] - 25s 64ms/step - loss: 1.6105 - accuracy: 0.5630 - val_loss: 2.2380 - val_accuracy: 0.4353
Epoch 6/50
391/391 [==============================] - 25s 64ms/step - loss: 1.2900 - accuracy: 0.6390 - val_loss: 2.2319 - val_accuracy: 0.4518
Epoch 7/50
391/391 [==============================] - 25s 64ms/step - loss: 1.0170 - accuracy: 0.7104 - val_loss: 2.4100 - val_accuracy:

In [ ]:
# Final evaluation of the model 
scores = model_1.evaluate(X_test, y_test, verbose=0) 
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 50.81%


In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix
pred = model_1.predict(X_test)
pred = np.argmax(pred, axis = 1) 
label = np.argmax(y_test,axis = 1)
r = confusion_matrix(pred, label)
print(r)

[[850  13  48  15  16  14   4  13  41  19]
 [ 15 865   5   9   3   5   2   4  26  62]
 [ 21   5 719  62  51  43  48  17   8   6]
 [ 14   1  42 600  40 143  36  32   6   8]
 [  9   2  81  62 778  50  24  35   9   4]
 [  1   8  27 118  22 655  18  28   2   7]
 [  7   4  48  60  34  24 855   6   1   3]
 [ 10   2  16  37  42  53   8 846   1   8]
 [ 54  29  10  19  11   9   4   6 896  27]
 [ 19  71   4  18   3   4   1  13  10 856]]
